### ISSUE TITLE
Dynamic locale and timezone setting entails a large overhead on portal.jsf

### ISSUE THREAD

**Issue by laborg** [phoenixctms/ctsms#10]
While analysing the performance of pages with Chrome devtools and Firefox, I stumbled upon the a large amount of html/js code that is generated, transferred, and to my knowledge not cached, in every page due to the locale and timezone selection. 

Example:

| Page  | Size |
|---|---|
| ecrfprogressoverview portal.jsf currently | ~329K|
| ecrfprogressoverview portal.jsf without locale&timezone | ~54K 6-fold decrease!|

Options how to deal with this:
- Moving this feature to a separate user page (preferred).
  - makes the ui cleaner
  - existing users might be confused if they lose functionality
- Javascript function to reload locale/time-changing-function on demand
  - less intrusive for current users
  - still a slight overhead for a feature which is rarely used? (at least that's the impression) 

Are there good reasons for having this feature? e.g. how many times are users expected to change their timezone?

**Comment by rkrenn** [comment]
so the verbose menu structure for timezone selection produces a huge chunk of markup (whith every single page request), while its actually hardly ever used. better to remove it then, good point.

**Comment by rkrenn** [comment]
disabled, see https://github.com/phoenixctms/ctsms/commit/95d18a672d766b9ff8b3e8f851c6a0b3c71b65a4

show_locale_menu=true
show_timezone_menu=false
