### ISSUE TITLE
Instalation not working, war not generated.

### ISSUE THREAD

**Issue by janijenko** [phoenixctms/ctsms#102]
Address of Spring repository should be changed from http to https. http://repo.spring.io/plugins-release/ doesn't work, https works. From January 15 2020, Spring’s Maven Repository doesn't support http.

**Comment by rkrenn** [comment]
thx for pointing.

https://github.com/phoenixctms/ctsms/commit/1bd5ac70e877b87f2cac6f6d498a8b8e051fce9f
