### ISSUE TITLE
blink() might be unused

### ISSUE THREAD

**Issue by laborg** [phoenixctms/ctsms#11]
The function `blink()` (`basetemplate.xhtml`) is set on each page to search for `blink`-tags and toggle their visibility every second. I couldn't find any use of a blink tag, so it might be possible to just remove this repeated function call. Besides the blink tag isn't endorsed any more. (https://developer.mozilla.org/de/docs/Web/HTML/Element/blink)

**Comment by rkrenn** [comment]
we had showcase eCRFs that demonstrated fancy blinking editcheck messages
for demonstration purposes. the support for the "blink" attribute was dropped
in browser quite some time ago and therefore a workaround by toggling visibility
with a timer was placed back then.

as you correctly pointed out, it is not used in the regular UI.
disabled now see https://github.com/phoenixctms/ctsms/commit/641f479c75852368593fd88181db1cb7cb9810da
