### ISSUE TITLE
Update/Assess javascript resources

### ISSUE THREAD

**Issue by laborg** [phoenixctms/ctsms#12]
Some javascript resources are not up to date, which could mean that there compatiblity with new browsers might be a problem. 
It would be helpful to minimize the usage of third party libraries (~software of unknown provenance). A javascript audit would be a good starting point. For corner cases, where a small feature might introduce a lot of javascript code the necessity of the features needs to be thoroughly reasoned.

**Comment by rkrenn** [comment]
we will enter validation steps with the settled javascript sources:

- primefaces 3.3.1 framework, with fixes and extensions: https://github.com/phoenixctms/ctsms/blob/master/web/src/main/webapp/resources/js/primefacesOverrides.js
- jquery fullcalendar v1.6.4 with fixes and extensions: https://github.com/phoenixctms/ctsms/blob/master/web/src/main/webapp/resources/js/jquery.fullCalendar.js
- d3 4.2.2
- jqplot and jquery plugins
- js-joda - 1.10.1
- Raphaël 2.2.0
- modified Raphael SketchPad Version 0.5.1
- Venn.js v0.2.14 wit fixes
