### ISSUE TITLE
Javascript and CSS resources aren't minified

### ISSUE THREAD

**Issue by laborg** [phoenixctms/ctsms#13]
Many Javascript/CSS resources are neither minified nor distributed in a packed fashion, which leads to longer loading times than necessary.

For often used combinations of Javascript resources, minifed and packed versions would be a welcomed performance improvement. The same holds for CSS files.

This addition should only be done after  https://github.com/phoenixctms/ctsms/issues/12

It could be implemented using a maven plugin: https://samaxes.github.io/minify-maven-plugin/ .

**Comment by rkrenn** [comment]
done.
