### ISSUE TITLE
how to test eCRFs

### ISSUE THREAD

**Issue by rkrenn** [phoenixctms/ctsms#143]
Hello, 

I am using the Phoenix CTMS software and I found a problem to test it. I don't know if there is a possible solution.

My problem is that when I create a trial with eCRFs, Visits, Patients, eCRF fields, etc., and I want to test if the functions or restrictions that I have put on the eCRF fields and eCRF inputs are well defined, I cannot test it because my Trial is in Design phase (i.e., I cannot introduce values in the eCRF Data Entry).

How can I check that the things I have created are well without changing the phase of the Trial?

**Comment by rkrenn** [comment]
we usually create a separate trial for developing/testing eCRFs.

to set it live, we export the eCRF setup ("Export eCRF Setup" in the trial's "Jobs" tab) in the test trial, and import it in the "production" trial ("Import eCRF Setup" in the trial's "Jobs" tab).

This way the test and production trial could even reside on different Phoenix CTMS instances.

**Comment by antonioPhD** [comment]
Thank you for the answer. 

However, I don't understand what we do that for. 
Once I've done the Export and Import, how can I use the imported Trial for simulating/testing as If I was using Phoenix for the Trial itself? 

What I need is going to eCRF Data Entry (in Design Mode) and be able to add values and see error messages and/or functions/code that I have written in the different eCRF inputs.

**Comment by rkrenn** [comment]
We have 2 trials, eg.:

1.	Trial „My TRIALXY *testing*“
2.	Trial „My TRIALXY *production*“

Then the workflow is as follows:

1.	We design/develop, review/review and *change* the eCRFs in Trial „My TRIALXY *testing*“. I.e. some complicated edit check code is being added or extended, which requires time and iterations, while the regular eCRF data entry (using the old eCRF versions without these new changes) has to continue without any interuption.
2.	Once signed off, we export the eCRF setup on Trial „My TRIALXY *testing*“, and import it on Trial „My TRIALXY *production*“.

This two steps are then repeated a soften as required during the lifetime of the Trial.
In the end, only „My TRIALXY *production*“ will contain the collected data.

**Comment by antonioPhD** [comment]
Now I see!

Thank you so much!
