### ISSUE TITLE
how to permanently delete an eCRF

### ISSUE THREAD

**Issue by rkrenn** [phoenixctms/ctsms#144]
Hello,

I'm designing a Trial (just for testing). Thus, I had to change the status of the Trial from Design to Carry out. 
Now, I want to remove a eCRF Field but when I try to do it, the eCRF Field doesn't disappear. It remains there, but crossed out, with the message: marked for deletion:

![grafik](https://user-images.githubusercontent.com/17864099/102551047-29412b00-40bf-11eb-931a-ba0cd1d4b06a.png)

How can I remove it completely? 

Thank you

**Comment by rkrenn** [comment]
if there is *no* data entered yet for you eCRF, and you use the default of

`ecrf_deferred_delete=false`

in your local overrides (/ctsms/properties/org/phoenixctms/ctsms/web/settings.properties), the eCRF will be dropped instantly.

otherwise, this could mean deleting a massive number of records (and creating a massing number of journal/audit trail records respectively), so there is this deferral mechanism. you can use `dbtool.sh` with the commandline switch below for removing the marked eCRFs finally:

```
D:\workspaces\ctsms\core\db>dbtool.bat --perform_deferred_delete_ecrf -u rkrenn -p ******

D:\workspaces\ctsms\core\db>"C:\Program Files\Java\jdk1.8.0_171\bin\java.exe" -DCTSMS_PROPERTIES="C:\ctsms\properties" -DCTSMS_JAVA="C:\ctsms\java" -Dfile.encod
ing=Cp1252 -Djava.awt.headless=true -classpath C:\tomcat\webapps\ctsms-web\WEB-INF\lib\ctsms-core-.7.0.jar;C:\tomcat\webapps\ctsms-web\WEB-INF\lib\* org.phoenix
ctms.ctsms.executable.DBTool --perform_deferred_delete_ecrf -u rkrenn -p ******
2020-12-18 00:00:21: starting...
CTSMS_PROPERTIES: C:\ctsms\properties
CTSMS_JAVA: C:\ctsms\java
Phoenix Clinical Trial Management System
version: 1.7.0
instance: CTSMS/phoenix.medunigraz.at
java.version: 1.8.0_171
java.home: C:\Program Files\Java\jdk1.8.0_171\jre
task: perform deferred delete of eCRF items
DB will be modified - eCRFs will be deleted!
type 'yes' to proceed:yes
0 ecrf entities marked for deletion
0 ecrf entities removed
2020-12-18 00:00:33: done - execution time: 12 seconds
```

you can register it as a cronjob on daily basis, if you want.

**Comment by rkrenn** [comment]
the same safety technique also applies when removing other massive object graphs:

```
course_deferred_delete=true
ecrf_deferred_delete=false
ecrf_field_deferred_delete=false
input_field_deferred_delete=false
inquiry_deferred_delete=false
inventory_deferred_delete=true
proband_deferred_delete=true
criteria_deferred_delete=false
selection_set_value_deferred_delete=false
staff_deferred_delete=true
trial_deferred_delete=true
user_deferred_delete=false
mass_mail_deferred_delete=true
```

**Comment by antonioPhD** [comment]
Thank you so much! 

In my case, I wanted to remove a eCRF Field and I had to add __field_ to the code:

D:\workspaces\ctsms\core\db>dbtool.bat --perform_deferred_delete_ecrf_field -u phoenix -p ******

**Comment by rkrenn** [comment]
>I had to add _field
👍
