### ISSUE TITLE
eCRF issues from form scripting vs. "hard" range checks

### ISSUE THREAD

**Issue by rkrenn** [phoenixctms/ctsms#145]
Hi again Rene, 

I'm creating an output expression for an eCRF Field. I want to create an Error message if the selected value from a dropdwon is NO.

I'm using: throw 'Error' ; (I also tried with throwError('Error');
But that doesn't create an error, but a warning message. I want to create an Error in order to avoid to continue adding values in other eCRFs, like in the example below:

![grafik](https://user-images.githubusercontent.com/17864099/102697648-b0191380-4237-11eb-84bb-1336222a2ade.png)

![grafik](https://user-images.githubusercontent.com/17864099/102697653-b9a27b80-4237-11eb-9318-caf5bf4dbbee.png)

**Comment by rkrenn** [comment]
there are 2 general kinds of input validations, described in https://www.researchgate.net/publication/325678636_Case_Report_Forms_using_Advanced_Form_Scripting 

(a) form scripting (see page 6, 10,11) messages that yield _eCRF issues_, to be resolved by the trial monitor.

![grafik](https://user-images.githubusercontent.com/17864099/102697872-9973bc00-4239-11eb-91bd-1906251c5771.png)

the eCRF cannot be closed down unless all discrepancies are resolved.

(b) _range checks_ of input fields (see page 54), which reject saving violating values:

![grafik](https://user-images.githubusercontent.com/17864099/102697916-012a0700-423a-11eb-9924-745751159026.png)

what you want then would be (b). however there is only a range control for multi-selection inputs, alllowing to specify the min/max number of selected items. so you could create a multi-selection item with one option only, and force the minimum selected items to 1.

as a general rule of thumb, the (a) technique is the preferred one: allow to safe anything, but then validate and raise a discrepancy.

**Comment by antonioPhD** [comment]
Thank you!

I took your advice and I created a multi-selection item with one option only
