### ISSUE TITLE
skip logic

### ISSUE THREAD

**Issue by rkrenn** [phoenixctms/ctsms#146]
I have another question:

How can I access the variable that contains the $disabled value. I would like to turn on and off the disabled tick of a eCRF Field depending on the entry of a previous value from another eCRF Input. 

Thank you

**Comment by rkrenn** [comment]
You can’t; the eCRF setup data model cannot be manipulated by form scripting.

Also „skip logic“ (showing/hiding or enabling/disabling fields depending on prior input) is not intended in Phoenix. Ie. for filled out pregnancy test data of subjects delcared „male“, you would rather raise discrepancy checks instead.
The paper-print eCRF should always contain all information.

**Comment by rkrenn** [comment]
> Ie. for filled out pregnancy test data of subjects delcared „male“, you would rather raise discrepancy checks instead.

pls find attached the setup for "pregancy test" sections extracted from some production eCRF. 

It demonstrates how to do validation checks instead of "skip clogic". 

you can import it into some separate testtrial and try it out directly.
[pregnancy_test_example.zip](https://github.com/phoenixctms/ctsms/files/5721015/pregnancy_test_example.zip)

**Comment by antonioPhD** [comment]
Thank you rkrenn!

I finally did it as it is shown in the _pregnancy_test_example.zip_

**Comment by rkrenn** [comment]
👍
