### ISSUE TITLE
how to reference parameters of eCRF_1 in eCRF_2

### ISSUE THREAD

**Issue by rkrenn** [phoenixctms/ctsms#147]
Hi, 

Is it possible to use a variable from another eCRF? 

For example:
In eCRF_1 I have the weight variable which contains the weight of the subject.
In eCRF_2 I need the weight of the subject for calculating the BMI. 

How can I access the variable weight in eCRF_1?

Thank you

**Comment by rkrenn** [comment]
for performance reasons for the _as-you-type_ calculations, the variables are partitioned by eCRF.
so you cannot access parameters of other eCRFs directly.

instead, there is the possibility to define _proband list attribute_ parameters. these will be exposed as "global variables" to eCRF form scripting. while vital params such as body weight are usually captured per visit, typical global variables exposed to eCRFs would be eg.

- subject id, lab id, ..
- informed consent date, screening date
- stratification parameter values
- randomization result

you can use the `findTagValues()` method to access proband attribute values, see https://github.com/phoenixctms/ctsms/blob/master/core/src/main/resources/fieldCalculation.js.

```
		mask["findTagValues"] = function(condition) {
			var result = [];
			if (_testFunction(condition)) {
				for ( var position in inputFieldVars.tagValues ) {
					if (condition(inputFieldVars.tagValues[position])) {
						result.push(_getInputFieldVariableValue(inputFieldVars.tagValues[position]));
					}
				}
			}
			return result;
		};
```

**Comment by antonioPhD** [comment]
Thank you for the answer!

I've created a proband_list_attribute but when I try to call it, I don't know how to do it. 
What is the condition? I've tried with the variable_name and also the ID. But it doesn't work. I don't know if I'm doing something wrong. 

I use the following code to check if I'm receiving the value, but I receive nothing:

function() {
  throw findTagValues(_variable_name_) ;
}

**Comment by rkrenn** [comment]
```
function(){
  throw findTagValues(function(tagValue) {
    console.log(tagValue);
    return (tagValue.inputFieldName == 'Befunde zuhause');
  }));
}
```

**Comment by antonioPhD** [comment]
Great!

Thank you so much!

**Comment by rkrenn** [comment]
👍
