### ISSUE TITLE
UI spinner element executes an ajax call for each interaction

### ISSUE THREAD

**Issue by laborg** [phoenixctms/ctsms#15]
When incrementing a value using a ui spinner element, the element executes ajax calls for each increment/decrement. 

1) Is this really necessary? Text input fields do not share this behaviour (e.g. when entering text no ajax call is registered)

2) If it is necessary, it might be better to apply deferred event execution. eg. to wait for a certain amount of time to make the ajax call (~250ms). If a new event is triggered within this time frame, the waiting starts anew.

**Comment by rkrenn** [comment]
which spinner are you referring to? there are 90+ defined, some of them sending changeevents via ajax, some not.

whithout overriding the primefaces ui:spinner component (at least the js part), event aggregation is available for ui:autocomplete only.

**Comment by laborg** [comment]
The spinner used for an integer field when entering ecrf data:
```
<input id="tabView:trialecrfstatusentry_form:ecrffield_inputs:0:section_inputs:1:integer0_input"
name="tabView:trialecrfstatusentry_form:ecrffield_inputs:0:section_inputs:1:integer0_input"
type="text"
class="ui-spinner-input ui-inputfield ui-state-default ui-corner-all"
autocomplete="off"
value="1"
onkeyup="FieldCalculation.integerOnChange('value1',0,inputFieldWidget_589500_0,'inputfield_output_589500_0')"
onchange="FieldCalculation.integerOnChange('value1',0,inputFieldWidget_589500_0,'inputfield_output_589500_0')"
role="textbox"
aria-multiline="false"
aria-valuenow="1"
aria-disabled="false"
aria-readonly="false">
```

I just don't understand the purpose of the call.

**Comment by rkrenn** [comment]
ok, below is the facelet code that produces the markup you showed. you can find it in inputFieldRow.xhtml.
`<p:spinner
id="integer#{index}"
widgetVar="#{fieldInput.widgetVar}"
value="#{fieldInput.longValue}"
label="#{fieldInput.label}"
rendered="#{fieldInput.integer}"
required="#{!optional and !fieldInput.optional}"
requiredMessage="#{fieldInput.requiredMessage}"
disabled="#{!enabled or fieldInput.disabled}"
styleClass="ctsms-spinner"
autocomplete="off"
onkeyup="#{fieldInput.getEventJSCall('FieldCalculation.integerOnChange')}"
onchange="#{fieldInput.getEventJSCall('FieldCalculation.integerOnChange')}">
<p:ajax />
<p:ajax event="keyup" />
</p:spinner>`

here several things are configured:
1. <p:ajax> is the notation to register a valuechange ajax update towards the managedbean's accessors, in this case the #{fieldInput.longValue}. usually primefaces components take care to minimize ajax requests  by leveraging onblur, onselect etc. sometime this is not too accurate, then a detailed ajax event is registered, like <p:ajax event="keyup" /> here. The reason for this ajax call is to keep the managedbean in an up-to-date state, to return consistent response at another point. When considering reducing ajax request frequency, it can be an option to revise the update topology of a particular managedbiean+accompanying facelet in detail. however the eCRF related parts already undego quite some optimizations oever time.

2. While only above cause true ajax requests, we here have the rare case where also the component's client (js) side event callbacks are utilized:

`{fieldInput.getEventJSCall('FieldCalculation.integerOnChange')}"
onchange="#{fieldInput.getEventJSCall('FieldCalculation.integerOnChange')}"`

The "FieldCalculation" js object is defined in fieldCalculation.js, where you can also find the function integerOnChange(). It will not cause any ajax request. It is responsible to update the field calculation value tree, so this is essentially placed to implement the evaluation "as-you-type" feature.

**Comment by rkrenn** [comment]
the ajax update events of all 38 p:spinner have been reworked, it will now trigger with onblur only.
for the ecrf form fields, this now aligns with the other field types (text field, date, ...)

the eCRF form field ajax update will update the value in the managed bean only (web tier), but currently not in the db (so the request time depends on jsf only). it would therefore be easy to persits to db to implement immediate persisting eg. before changing the page. the reason to send values via ajax is to not loose values when changing the layout ("from fields per row"), or to be able to run into session timeout as soon as possible.

regarding request response times, they in fact essentially depend on the jsf component tree size the element is part of. a p:spinner ajax request takes eg.
- 30-40 ms in the course main tab
- 40 ms in the eCRF section-only view (when opening it vie eCRF issues)
- 260ms in the eCRF date entry view of a proband
- 400ms in the eCRF data entry view of a trial
