### ISSUE TITLE
Error performing 'TrialService.setEcrfStatusEntry(AuthenticationVO auth, Long probandListEntryId, Long ecrfId, Long visitId, Long version, Long ecrfStatusTypeId, Long probandListStatusEntryId)'

### ISSUE THREAD

**Issue by antonioPhD** [phoenixctms/ctsms#153]
Hello, 

Sometimes when I want to change the eCRF status from "status: in progress" to "satus: input validation" it appears the following message.

_Error performing 'TrialService.setEcrfStatusEntry(AuthenticationVO auth, Long probandListEntryId, Long ecrfId, Long visitId, Long version, Long ecrfStatusTypeId, Long probandListStatusEntryId)' --> java.lang.AssertionError: Failed generating bytecode for <eval>:5_

Sometimes it appears and sometimes it doesn't appear. 
I don't understand what the problem is. Can you help me?

**Comment by rkrenn** [comment]
Nashorn JS engine is running out of stack size -> https://stackoverflow.com/questions/58636947/some-problem-aboutjdk-nashorn-errorfailed-generating-bytecode-for-eval1

fix see https://github.com/phoenixctms/install-debian/commit/6a625655517a8f3ab88d7bdba2f75ad9f7e2fd74

**Comment by rkrenn** [comment]
you need to change the -Xss option arg in the file /etc/default/tomcat8 form

`-Xss256k`

to

`-Xss512k`

(or more), then restart tomcat.

**Comment by antonioPhD** [comment]
Thank you so much!
