### ISSUE TITLE
eCRF Data Export ERROR

### ISSUE THREAD

**Issue by antonioPhD** [phoenixctms/ctsms#154]
Hello, 

I want to export the eCRF Data from a Trial. 
I used the command that is shown in **eCRF Data Export** section of the [web page](https://www.phoenixctms.org/features/modules/trials/ecrf/) :

phoenix@phoenix:~$ sudo -u ctsms /ctsms/ecrfdataexport.sh --id=XXXXXX \
> --task=cleanup_all \
> --task=export_ecrf_data_vertical \
> --task=export_ecrf_data_horizontal \
> --task=publish_ecrf_data_sqlite \
> --task=publish_ecrf_data_horizontal_csv \
> --task=publish_ecrf_data_xls \
> --task=publish_ecrf_data_pdfs \
> --task=publish_audit_trail_xls \
> --task=publish_ecrf_journal_xls \
> --task=publish_ecrfs_xls \
> --force

In id=XXXXX I added the number of the trial from which I want to export the data. 

And I have the following error message:

_WARN - Trial eCRF export/data aggregation:_

_working directory cleanup error
Trial eCRF export/data aggregation:_

_working directory cleanup error at /ctsms/bulk_processor/CTSMS/BulkProcessor/Projects/ETL/EcrfExporter/process.pl line 276._

Can someone help me with that please?

Thank you

**Comment by rkrenn** [comment]
i presume there is a file permission issue.

pls raise the file_loglevel in your /ctsms/bulk_processor/CTSMS/BulkProcessor/Projects/ETL/EcrfExporter/config.cfg to DEBUG, then retry and grab the details at the end of the latest file in the /log subdir of the "working_path" folder.

**Comment by rkrenn** [comment]
```
cannot chdir to /root from /ctsms/bulk_processor/output/ecrf_exporter/output: Permission denied, aborting. at /ctsms/bulk_processor/CTSMS/BulkProcessor/Utils.pm line 589.
```

**Comment by rkrenn** [comment]
fixed by https://github.com/phoenixctms/bulk-processor/commit/8aff95226fd596a9d40e483b94ed78d8ee9d9702

**Comment by rkrenn** [comment]
you would just need to replace /ctsms/bulk_processor/CTSMS/Utils.pm with the updated one.

**Comment by antonioPhD** [comment]
I used the following command: 

 _/ctsms/ecrfdataexport.sh --id=XXXXX_ [...]

without _sudo -u ctsms_

And it worked!

**Comment by rkrenn** [comment]
you could have also change the current directory before executing the command.

>without sudo -u ctsms

you should avoid that, as it means created files and directories will hot have permissions fro ctsms user, hence you could run into other problem later.

better just replace that fixed Utils.pm.
