### ISSUE TITLE
Problem with IP-Configuration

### ISSUE THREAD

**Issue by codonAG** [phoenixctms/ctsms#155]
I have a problem with the VM.
If i restart the physical server where the VM is on then it lost the IP-Configuration. The same problem is, when I change the configuration in /etc/network/interfaces.
Is there a workaround or a solution?

**Comment by rkrenn** [comment]
debian by default obtains a dynamic IP using dhcp.

you would need to configure a static IP address, eg. described here https://linuxconfig.org/how-to-setup-a-static-ip-address-on-debian-linux

**Comment by codonAG** [comment]
Thank you for the quick response but exactly that I did before but the Web-GUI of phoenix is not reachable.

**Comment by rkrenn** [comment]
i can confirm the procedure below works:

1. set the bridged eth device from "dhcp" to "static", and provide the static IP address settings. so the `/etc/network/interfaces` file will look like this:

```
...

# The loopback network interface
auto lo
iface lo inet loopback

# The primary network interface
allow-hotplug enp0s3
iface enp0s3 inet static
      address 192.168.0.123
      netmask 255.255.255.0
      gateway 192.168.0.1
```

2. Apply the changes. `service networking restart` did noit work for me, and i didnt try to disable/enable using `ip link set enp0s3 down/up` either, but a simple **reboot** helped. This way http services (apache2, tomcat8) will also be properly bound.

**Comment by codonAG** [comment]
Thank you.
I find the solution. 
I write "ip a" and found out that the name is not enp0s3 but ens3.
I changed the name in /etc/network/interfaces to ens3 and now it works.

**Comment by rkrenn** [comment]
👍
