### ISSUE TITLE
Replace jquery.base64.js with native functions

### ISSUE THREAD

**Issue by laborg** [phoenixctms/ctsms#16]
No need to carry around a base64 encoder/decoder:
https://developer.mozilla.org/en-US/docs/Web/API/WindowBase64/Base64_encoding_and_decoding#Solution_2_%E2%80%93_escaping_the_string_before_encoding_it appears to be easier

**Comment by rkrenn** [comment]
we cant use native functions like window.btoa in fieldClaculation.js, which is also executed by rhino/nashorn.
