### ISSUE TITLE
date objects in form scripting

### ISSUE THREAD

**Issue by rkrenn** [phoenixctms/ctsms#162]
Hello, 

I'm doing some testing and I've put the same code that you have in the website:

```
function() {
  if (!empty($enteredValue)) {
    var today = new Date();
    var year1 = today.getUTCFullYear();
    var year2 = $enteredValue.getUTCFullYear();
    var month1 = today.getUTCMonth() + 1;
    var month2 = $enteredValue.getUTCMonth() + 1;
    var day1 = today.getUTCDate();
    var day2 = $enteredValue.getUTCDate();
    var age = year1 - year2;
    if (month2 > month1) {
      age--;
    } else if (month1 == month2 && day2 > day1) {
      age--;
    }
    if (age < 5) {
      throwError('subject is younger than 5 years');
    }
    return sprintf('age: %d years',age);
  }
}
```

However, when I check if the code is correct, it appears the following message in the eCRF Data Entry window:

![grafik](https://user-images.githubusercontent.com/17864099/109368145-6f252700-7898-11eb-90a4-3a63481a1c63.png)
 
Why doesn't it work? Do I need to add something? 

Thank you

**Comment by rkrenn** [comment]
in order to properly support user timezones, date objects in form-scripting were migrated from javascript native Date to **JSJoda**: 

- https://github.com/phoenixctms/ctsms/commit/cd06f8c9116f0e82cf346919224b2541d2e25f83#diff-8ebb127fa7882a828b3829903515464bac8b6b6f30d4a2943fd4311f27d86835
- https://github.com/phoenixctms/ctsms/commit/a095dc6b636d96903bf21f225a0542f9fd353a79#diff-8ebb127fa7882a828b3829903515464bac8b6b6f30d4a2943fd4311f27d86835

the age calculation example would therefore look like this:

```
function() {
  if (!empty($enteredValue)) {
    var today = JSJoda.LocalDate.now();
    var year1 = today.year();
    var year2 = $enteredValue.year();
    var month1 = today.monthValue();
    var month2 = $enteredValue.monthValue();
    var day1 = today.dayOfMonth();
    var day2 = $enteredValue.dayOfMonth();
    var age = year1 - year2;
    if (month2 > month1) {
      age--;
    } else if (month1 == month2 && day2 > day1) {
      age--;
    }
    if (age < 5) {
      throwError('subject is younger than 5 years');
    }
    return sprintf('age: %d years',age);
  }
}
```

see https://js-joda.github.io/js-joda/ for details on how to use JSJoda date&time objects.

**Comment by VeitWeber** [comment]
@rkrenn Sorry, saw your anwser just now. I also came to your conclusion.

**Comment by rkrenn** [comment]
👍 

feel free to re-open if needed.
