### ISSUE TITLE
software validation

### ISSUE THREAD

**Issue by codonAG2** [phoenixctms/ctsms#163]
Hi,
Has the Phoenix CTMS software been validated externally? Is there documentation on this? Could not find anything on the homepage that is why I am asking here.

Best regards

**Comment by rkrenn** [comment]
hi!

yes, there are CROs that validated particular usecases for their purposes.

regarding software validation, the URS can be found at https://www.researchgate.net/publication/263412137_Design_and_Development_of_a_Web-Based_Clinical_Trial_Management_System. Pls note that it reflects the outdated state as of 2014.

establishing the github ecosystem (issue tracking, java CI, sonarcloud code analysis, ...) was our main part to establish documentation of the software development process and quality control.

the debian stretch installation procedure reflects a standardized installation qualification.

for performance qualification regards, you can check out the provided sample testsuite forbasic usecases. it can be launched using `sudo -u ctsms /ctsms/dbtool.sh --load_demo_data`.

pls contact us directly if you need more assistance with the infrastracture provided (or documenting it).

br & schöne Grüße aus Österreich
