### ISSUE TITLE
RAM problem with Phoenix CTMS

### ISSUE THREAD

**Issue by rkrenn** [phoenixctms/ctsms#165]
Hi!

My name is .., I'm a software engineer. One of my mates is using your CTMS for research and I helped him to deploy Phoenix in a Digital Ocean droplet. The problem is that sometimes the tomcat8 service shutdowns, due to lack of RAM (we have 4 GB). I tried to limit the use of RAM setting the parameters -Xms2048m -Xmx3072m in /etc/default/tomcat, but we still have problems. Do you have any suggestions?

Thank you very much!

Best,

**Comment by rkrenn** [comment]
obviously your instance seem to serve a lot of users then, so you should increase ram of the virtual machine and tomcat8 jvm memory. with too less memory, the phoenix webapp/tomcat8 is known to continously looses performance, usually until it stops responding. 

we use e.g. instances with 18GB RAM / 6vCPUs@2.5GHz, capable of serving 25 active users at the same time. 365days/year uptime.

**Comment by MillerEsp** [comment]
Thanks for replying.

We only have between 1 and 2 active users. There is a way to prevent that stop of the service even if we lose performance? I'm not an expert with tomcat and these kind of software applications.

Thank you again.

**Comment by rkrenn** [comment]
first verify if the memeory is the problem: pls paste sections of catalina.out and linux kernel messages (dmesg) at the time of the service interrruption.

then try to increase system RAM, jvm heap (-Xmx), space for permanent generation object (-XX:MaxPermSize).
i think antonio also once reported an error message regarding rhino engine exceeding jvm stacksize, so also increase that (-Xss).

then let's seeh if the issue persists.

**Comment by MillerEsp** [comment]
Hi!

Sorry for late response. I couldn’t get these files just after a service interruption until know.

I will try with the configuration you recommended to us.

On the other hand, we have a dropbox service to upload backups, maybe this can cause some RAM problems.

Thank you.

[files.zip](https://github.com/phoenixctms/ctsms/files/6154673/files.zip)
