### ISSUE TITLE
ecrfdataexport.sh "password expired"

### ISSUE THREAD

**Issue by rkrenn** [phoenixctms/ctsms#166]
Hi, 

I tried to export data from the eCRF, but I had the following ERROR:

`ERROR` - my_department_cron@http://127.0.0.1:8080 - 401 : password expired`

I have already changed the password but the problem's still there. 

The code I run when the error appears is: 

```
/ctsms/ecrfdataexport.sh --id=XXXXXX \
--task=export_ecrf_data_vertical \
--task=export_ecrf_data_horizontal \
--task=publish_ecrf_data_sqlite \
--task=publish_ecrf_data_horizontal_csv \
--task=publish_ecrf_data_xls \
--task=publish_ecrf_data_pdfs \
--task=publish_audit_trail_xls \
--task=publish_ecrf_journal_xls \
--task=publish_ecrfs_xls \
--force
```

How can I fix that?

Thanks,

**Comment by rkrenn** [comment]
set a new password for the "my_department_cron" user:

![grafik](https://user-images.githubusercontent.com/17864099/111491677-59d74600-873c-11eb-8e86-f6196617815d.png)

you might want to disable "Expires" here this time.

**Comment by rkrenn** [comment]
you afterwards also need to update the Bulk-Processor .cfg files taht refer the credentials:

```
phoenix@phoenix:~$ sudo grep my_department_cron /ctsms/bulk_processor/ -R --include=*.cfg 
/ctsms/bulk_processor/CTSMS/BulkProcessor/Projects/ETL/Duplicates/config.cfg:ctsmsrestapi_username = my_department_cron
/ctsms/bulk_processor/CTSMS/BulkProcessor/Projects/ETL/EcrfExporter/config.job.cfg:ctsmsrestapi_username = my_department_cron
/ctsms/bulk_processor/CTSMS/BulkProcessor/Projects/ETL/EcrfExporter/config.cfg:ctsmsrestapi_username = my_department_cron
/ctsms/bulk_processor/CTSMS/BulkProcessor/Projects/ETL/InquiryExporter/config.job.cfg:ctsmsrestapi_username = my_department_cron
/ctsms/bulk_processor/CTSMS/BulkProcessor/Projects/ETL/InquiryExporter/config.cfg:ctsmsrestapi_username = my_department_cron
/ctsms/bulk_processor/CTSMS/BulkProcessor/Projects/ETL/Criteria/config.cfg:ctsmsrestapi_username = my_department_cron
```

**Comment by ABiomec** [comment]
Hi, 

I've changed the "my_department_cron" password. I've changed even the "my_department_signup_en" and "my_department_signup_de" password. I've done the update of the Bulk-Processor .cfg files too. 

But now I have the following error:

ERROR - my_department_cron@http://127.0.0.1:8080 - 401 : wrong password ********

**Comment by rkrenn** [comment]
then also try to log in with the "my_department_cron" user in the UI.

**Comment by ABiomec** [comment]
It doesn't work. The error persists

**Comment by rkrenn** [comment]
it means you were able to log into the UI with the new password for "my_department_cron".

the config.cfg files each have a section like below:

```
##ctsms REST-API connectivity:
ctsmsrestapi_uri = http://127.0.0.1:8080/rest
ctsmsrestapi_username = my_department_cron
ctsmsrestapi_password = 123456...
ctsmsrestapi_realm = api
```

and the `ctsmsrestapi_password` parameter above was changed to the new password in each of

```
/ctsms/bulk_processor/CTSMS/BulkProcessor/Projects/ETL/Duplicates/config.cfg
/ctsms/bulk_processor/CTSMS/BulkProcessor/Projects/ETL/EcrfExporter/config.job.cfg
/ctsms/bulk_processor/CTSMS/BulkProcessor/Projects/ETL/EcrfExporter/config.cfg
/ctsms/bulk_processor/CTSMS/BulkProcessor/Projects/ETL/InquiryExporter/config.job.cfg
/ctsms/bulk_processor/CTSMS/BulkProcessor/Projects/ETL/InquiryExporter/config.cfg
/ctsms/bulk_processor/CTSMS/BulkProcessor/Projects/ETL/Criteria/config.cfg
```

in the journal of the "my_department_cron" user you can find details of the failed logins.
in the database table "error" you can find more details on the failed authentication, in particular it also records the provided parameters (credentials) of the failed operation.

**Comment by ABiomec** [comment]
Now it's solved! 
I changed the password of the "my_department_cron" user using the default password that appears in the config.cfg file. 

Thank you

**Comment by rkrenn** [comment]
👍
