### ISSUE TITLE
eCRF Export Issue

### ISSUE THREAD

**Issue by rkrenn** [phoenixctms/ctsms#168]
Hello, 

When I use the code for exporting the eCRF Data (specially for getting the ecrf_data_horizontal), some of the data is not exported. I don't get any error message (apparently) and I don't know why the exported file is half finished.

I've seen that the size of the .csv file is always 120KB. Is there any restriction for the size of the file?

```
/ctsms/ecrfdataexport.sh --id=XXXXXX \
--task=cleanup_all
--task=export_ecrf_data_vertical
--task=export_ecrf_data_horizontal
--task=publish_ecrf_data_sqlite
--task=publish_ecrf_data_horizontal_csv
--task=publish_ecrf_data_xls
--task=publish_ecrf_data_pdfs
--task=publish_audit_trail_xls
--task=publish_ecrf_journal_xls
--task=publish_ecrfs_xls
--force
```

Thanks

**Comment by rkrenn** [comment]
there is no filesize restriction of course.

pls check: 
1. does the number of rows in you .csv match the number of subjects you have
2. does the number of eCRF fields match the number of columns in your .csv

**Comment by ABiomec** [comment]
1. The number of rows match with the number of subjects
2. The number of columns is around 7.153, and the number of eCRF fields is 373.

I would say that the .csv has the correct size. The problem is that some eCRF Fields that are filled out in the Phoenix Software don't appear in the .csv file. It appears the variable but not the value entered (the cells are empty).

**Comment by rkrenn** [comment]
>It appears the variable but not the value entered (the cells are empty).
can you show in detail what you think is missing.

did you configure your own "External ID" names for the eCRF fields?

>The number of columns is around 7.153, and the number of eCRF fields is 373.
this indicates you have series sections, such as concommitant thickness.
each column will also have an index there. if your subjects have eg. 20 thinesses entered at most,
the index will reach 20. columns will however be mostly empty for subjects with less thicknesses.

**Comment by ABiomec** [comment]
For example:

Here, there is the time a patient needs to complete a walking test:

![image](https://user-images.githubusercontent.com/75142713/112720229-622e3e80-8efd-11eb-9266-7858e4d0b8be.png)

As you can see, the value is entered and saved. It's even reviewed. 

And this is the same test but done in a later session:

![image](https://user-images.githubusercontent.com/75142713/112720190-272c0b00-8efd-11eb-9fe3-9f3de482c6cd.png)



When I export the Data, only the first session is exported, but not the second one:

![image](https://user-images.githubusercontent.com/75142713/112720272-973a9100-8efd-11eb-89db-268cb5f00b81.png)

![image](https://user-images.githubusercontent.com/75142713/112720294-b2a59c00-8efd-11eb-8e47-55960c612418.png)




They are the same eCRF, with the same eCRF Fields. They're different sessions though.

**Comment by rkrenn** [comment]
can you send the eCRF setup (at least including the 2 topical fields)

**Comment by ABiomec** [comment]
What do you mean with "eCRF setup"?

**Comment by rkrenn** [comment]
this:

![grafik](https://user-images.githubusercontent.com/17864099/112721008-ea164780-8f01-11eb-88c2-3790d7445c26.png)

from the generated .xsl you can then remove all lines form the "ecrffields" spreadsheet, except the 2 you were looking at.

**Comment by ABiomec** [comment]
It is okey with this?: 

[612141.xlsx](https://github.com/phoenixctms/ctsms/files/6215661/612141.xlsx)

**Comment by rkrenn** [comment]
thx.
eventually you discovered a regression with latest "multi-visit" eCRFs change, which we have not yet use in production.

will come back to you later tonite.

**Comment by rkrenn** [comment]
ok i was able to reproduce the issue

**Comment by rkrenn** [comment]
https://github.com/phoenixctms/bulk-processor/pull/8
