### ISSUE TITLE
User selectable theming might cause problems

### ISSUE THREAD

**Issue by laborg** [phoenixctms/ctsms#18]
Currently there is the possibility for a user to select the theme. Not all themes appear usable and validation effort grows with the amount of themes. Further on it adds 16Kb markup to each page.  

- It should be possible to completely disable user theming (e.g. with a property setting).
- And if its enabled it might be better positioned on the extended user page (where timezone and locales are configured)

**Comment by rkrenn** [comment]
ack, pls provide the list of themes to remove (or keep).

**Comment by laborg** [comment]
Revisiting this, it might be better to just support a single theme.

**Comment by rkrenn** [comment]
there are several themes known to work with no display discrepancies (aristo, casablanca, sunny to name a few).

to restrict to one particular theme, remove all but the desired one from themes.properties.

so i think this can be closed.
