### ISSUE TITLE
Phoenix CTMS Server time zone

### ISSUE THREAD

**Issue by codonAG2** [phoenixctms/ctsms#183]
Hi,

Is there an option to change the Phoenix CTMS Server time zone and if so, could you explain how?
I am asking because in excel or PDF exports of CRF data we have the issue that time stamps and data fields related to time are not exported in the user time format but rather in UTC time zone (server time zone?). We would like to have this data exported in our chosen time zone.

Thanks,
codon

**Comment by rkrenn** [comment]
merging part 1 of 3: PR #184 "user timezones in PDF documents"

**Comment by rkrenn** [comment]
merging part 2 of 3: PR #189 "timezone conversion support for Rest-API"

**Comment by rkrenn** [comment]
merging part 3 of 3: PR #195 "user timezones in XLS documents"

**Comment by rkrenn** [comment]
finally we can make use of the timezone conversion of the restapi in the data exporters: https://github.com/phoenixctms/bulk-processor/pull/11

**Comment by rkrenn** [comment]
summary & proof:

1. Server Timezone "Euroe/Vienna", User Timezone "US/Hawaii"
2. eCRF with 2 fields of timestamp type:

![grafik](https://user-images.githubusercontent.com/17864099/148096931-c6037428-d25b-449d-bcfb-7b019574481e.png)

(a) 1st one expecting timestamps antered in user timezone
(b) 2nd one for abolute timestamps (server time) 

3. values persisted in the database:

![grafik](https://user-images.githubusercontent.com/17864099/148098093-0c4aef14-a3da-44a3-954a-e8ce5153000d.png)

4. Old behaviour: eCRF data export without timezone conversion:

![grafik](https://user-images.githubusercontent.com/17864099/148098439-8615dd1f-bc49-44b0-83b6-44e3d4fcbbf5.png)

5. New behaviour: eCRF data export with timezone conversion:

![grafik](https://user-images.githubusercontent.com/17864099/148098683-1f4caae4-6157-4c90-8dba-e1c09e260921.png)

**Comment by rkrenn** [comment]
tests for Inquiry data export and eCRF data importer also successful

**Comment by rkrenn** [comment]
merged bulk-processor part https://github.com/phoenixctms/bulk-processor/pull/11

**Comment by rkrenn** [comment]
enabled by merging https://github.com/phoenixctms/ctsms/pull/196

feature implemented.
