### ISSUE TITLE
Separate build and deploy

### ISSUE THREAD

**Issue by laborg** [phoenixctms/ctsms#19]
The `install.sh` script includes a lot of different tasks:
 - adding of phoenix ctsms user
 - installing necessary deb packages
 - installing necessary perl packages
 - fetching, building and installation of bulkprocessor
 - fetching, building and installation of bulkprocessor
 - database setup and configuration
 - apache setup and configuration
 - creating the server certificate
 - initialization of phoenix 
 - ...

These tasks need to be split up to
 - make the use case of having one system per study viable efficient/automizable.
 - integrate phoenix into a continuous integration system.

### Building Phoenix
 - maven based build
 - output: `.war`, db_schema_changes

### Building Bulkprocessor
 - packaging perl modules as executable with minimum prerequisites
 - output: ideally something like a jar/war

### System/OS Setup
 - once per system / no configuration per study
 - installation, configuration and validation of
   - postgres
   - apache
   - tomcat
   - java
 - output: installation log file

### StudyGroup Setup
 - once per system / configuration per StudyGroup certificate, branding, "master data"
 - creation and deployment of server certificate
 - deployment of Phoenix/Bulkprocessor
 - initialization of Phoenix

### Update
 - multiple times per system / no configuration
 - deployment of updated war
 - application of any upgrade/downgrade SQL scripts

## Open questions:
 - Bulkprocessor is used to render workflow state images after data has been loaded. This tight integration of build/deployment/operation complicates the matter. Maybe its better to replace the perl rendering with java (https://github.com/nidi3/graphviz-java), and call this on server start.  
 - Bulkprocessor, as a perl application, depends on a mix of debian packages, third party package management system(s) and tools. To allow validation of a system, it is necessary to have a way to reproducible build and deploy the Bulkprocessor. My perl knowledge is limited, but maybe this could be used: https://metacpan.org/pod/PAR::Tutorial

**Comment by rkrenn** [comment]
install and update is automated nowadays.
