### ISSUE TITLE
phoenix on windows

### ISSUE THREAD

**Issue by rkrenn** [phoenixctms/ctsms#208]
Hi,

I’m taking a look about your application just because we need an good app for CTMS.

I have been spending last few days to get your system working on Windows platform.. instructions that exists on Git are a kind of short.
Luckily there is a Debian install repo to get some hints what is needed 😊. I’m forced to use Windows for other application requirements.

Got it running eventually on Server 2022 virtual machine. Some issues though.. I could have created an issue but there are more than one to clear up.

First of all.. Sample files on master-data.. are there any English versions? Some of them seems to be more or less AT specific.

What I’m missing as no modules are enabled:

![grafik](https://user-images.githubusercontent.com/17864099/154016648-84776c8f-8ade-46e6-81bc-6d595fb99469.png)

.. should’nt “phoenix” be superuser? This is kind of a block for my evaluation.

I could/would contribute Finnish (and maybe Swedish) translations to the project. ..but there seems to be new release on the way. Should I be wait for that?

Some proposal for new versions to come.
If using Postgres (or any other db) on non-standard settings. I do have another app in port 5432 and took some time to figure out how to get that defined. Java is not my bread and butter.. I’m more Visual Studio person. Same goes for database credentials. Would be nice to have .config file outside the build to set some environment variables. By default username and pwd are the same and that is not very safe.. and those are not handy to configure, or to change.
DBTool was also “fun” to get working without proper instructions 😊

br

**Comment by rkrenn** [comment]
Hi,

>I’m forced to use Windows for other application requirements.

I see, we are developing the webapp also mainly in windows (both java and perl parts)

> First of all.. Sample files on master-data.. are there any English versions? Some of them seems to be more or less AT specific.

In general the application can be fully localized.
The address, substance (ASP), disease (ICD-10) and procedure (OPS) catalogues from the master-data repo are AT/German.
It is a matter of getting source data. I managed to eg. load an english ICD-10 code variant. I found it again, see attachment.

[icdClaML2016ens.zip](https://github.com/phoenixctms/ctsms/files/8066901/icdClaML2016ens.zip)

>What I’m missing as no modules are enabled:

On your (windows etc.) deplyoment you also need to place your configuration overloads.

![grafik](https://user-images.githubusercontent.com/17864099/154016804-53ebf0f2-609c-4701-96c9-453107892dc1.png)

You should set a environment variable CTSMS_PROPERTIES pointing to a folder with overrides for any .properties variables, see eg. https://github.com/phoenixctms/config-default/tree/master/properties . With latter example yconfig, you will also see the modules enabled.

You optionally can specify an environment variable CTSMS_JAVA pointing to a folder with overrides for any .java class (yes it will be dynamically compiled and loaded..), see eg. https://github.com/phoenixctms/config-default/tree/master/java/ (in case you need that one day).

> Same goes for database credentials. Would be nice to have .config file outside the build to set some environment variables.

Just add your credentials in your .properties override of ctsms-applicationcontext.properties:
https://github.com/phoenixctms/config-default/blob/master/properties/ctsms-applicationcontext.properties

```
database_username=ctsms
database_password=ctsms
database_connection_url=jdbc:postgresql://localhost/ctsms
c3p0.acquireIncrement=3
c3p0.initialPoolSize=10
c3p0.minPoolSize=5
c3p0.maxPoolSize=30
c3p0.maxIdleTime=300
c3p0.maxStatementsPerConnection=200
```

> I do have another app in port 5432 and took some time to figure out how to get that defined.

You can specify the port as part of the database_connection_url variable from above.

> I could/would contribute Finnish (and maybe Swedish) translations to the project.

You are welcome, see https://github.com/phoenixctms/ctsms/issues/173 
be aware that it is a lot to translate.

> but there seems to be new release on the way. Should I be wait for that?

Will add 1.8.0 release tags after merging remaining PRs https://github.com/phoenixctms/ctsms/pulls 
So current master branch is pretty much what there will be in 1.8.0, no need to hesitate.

Best regards,
rene

**Comment by josharmenta** [comment]
@rkrenn Maybe we should look at setting up Crowdin for localization? https://crowdin.com/
It's free for open source projects.

**Comment by rkrenn** [comment]
yes, /me stumbled upon that too allready. do you want to help me with that?
here i summarized the localization files: https://github.com/phoenixctms/ctsms/issues/173

**Comment by viiliainen** [comment]
Crowdin says : Project does not exist or access to this project is limited.

**Comment by rkrenn** [comment]
setup was not yet complete, try this link:
https://crowdin.com/project/phoenix-ctms/invite?d=957556u4m6v627a343c3e363s4

**Comment by rkrenn** [comment]
ah, pls hold on, we still need to un-suspend crowdin

**Comment by rkrenn** [comment]
i also had to change it to a public project, now it is visible:
https://crowdin.com/project/phoenix-ctms

**Comment by rkrenn** [comment]
crowdin is set up for the project, but currently now resources for any windows installation deep-dives.
