### ISSUE TITLE
Expose states/provinces in UI?

### ISSUE THREAD

**Issue by josharmenta** [phoenixctms/ctsms#219]
Hi Rene,

Thanks again for all your work on this. I'm really enjoying figuring it out.

Is there a way to expose a States/Provinces dropdown in both the backend and the signup UI? I don't hacking the feature in myself if you point me in the right direction, but I'm not a Java guy. 

Thanks!

**Comment by rkrenn** [comment]
during installation, the catalogues for postal addresses are imported from 

https://github.com/phoenixctms/master-data/blob/master/countries.txt
https://github.com/phoenixctms/master-data/blob/master/streetnames.csv

so there you could use the "country" element for that (ie. "us_ca" or "California").

if you prefer a dedicated field for that, we need a _feature request_.
we can do so, i currently see no objections with adding a new database column for state/province.

the catalogues are also exposed via rest-api. http://<hostname>/rest/tools/complete/
documentation: [complete_api.zip](https://github.com/phoenixctms/ctsms/files/8379882/complete_api.zip)

**Comment by josharmenta** [comment]
Thanks Rene, I can raise a PR to add the field later, probably in a week or two.

**Comment by rkrenn** [comment]
@josharmenta implementation is complete, please give it a try.

the state/province field is enabled by default and can be controlled in /ctsms/properties/org/phoenixctms/ctsms/web/settings.properties:

```
proband_address_show_province=true
staff_address_show_province=true 
```

![grafik](https://user-images.githubusercontent.com/17864099/169003938-9aec51de-c6d0-4bb6-8842-0f3dd47a8d7f.png)

Signup WebApp:

![grafik](https://user-images.githubusercontent.com/17864099/169004170-8a44b20f-250b-4bc5-ae9f-5edb1be39728.png)
