### ISSUE TITLE
Service unavailable

### ISSUE THREAD

**Issue by milleresp** [phoenixctms/ctsms#230]
Hello!

I was trying to install phoenix in my computer with Virtual Box. I've tried it with the prepared .ova package and installing it in an ubuntu OS, but I always have the message of "Service unavailable". When I did it with ubuntu, I executed each line inside install.sh by myself and there were not errors. I've also checked tomcat9 and apache2 services and they are running.

The virtual machine has more than 8GB of RAM.

Do you know what can I do to solve the problem? Thank you very much!

**Comment by rkrenn** [comment]
thanks for pointing.
just reverted https://github.com/phoenixctms/install-debian/commit/9e957fd631621a5d2ca4cceddc5a005ea652a9a9
