### ISSUE TITLE
Hint for those of us who are using Citrix

### ISSUE THREAD

**Issue by josharmenta** [phoenixctms/ctsms#235]
We are deploying this app in a subnet that can only be accessed thru Citrix XenDesktop and I needed to be able to deploy a shortcut to Phoenix, but couldn't use Google Chrome Kiosk mode since that would interfere with another app we're using in our trial. 

I was able to build an app that was exactly restricted the way I needed using Nativefier:

`nativefier 'address-of-dev-server' -n 'Phoenix CTMS' --ignore-certificate=true --insecure=true --internal-urls 'address-of-dev-server.*' 'address-of-dev-server'`

For `address-of-dev-server` I just put the address without the `https://`

This basically makes an Electron app that is hard-coded to launch the Phoenix web site, which is exactly what we needed.

<img width="939" alt="image" src="https://user-images.githubusercontent.com/8599486/169673899-cc9614ac-d753-43a7-8f1a-19de8a499315.png">

**Comment by rkrenn** [comment]
Excellent, thx a lot for sharing!
