### ISSUE TITLE
the link and credentials NOT printed at last

### ISSUE THREAD

**Issue by carebmc** [phoenixctms/ctsms#237]
Just built from master branch following instructions. but no login info was printed.

```
[INFO] --- maven-war-plugin:3.2.2:war (default-war) @ ctsms-web ---
[INFO] Packaging webapp
[INFO] Assembling webapp [ctsms-web] in [/ctsms/build/ctsms/web/target/ctsms-1.8.1]
[INFO] Processing war project
[INFO] Copying webapp resources [/ctsms/build/ctsms/web/src/main/webapp]
[INFO] Webapp assembled in [2922 msecs]
[INFO] Building war: /ctsms/build/ctsms/web/target/ctsms-1.8.1.war
[INFO]
[INFO] --- andromdapp-maven-plugin:3.4:deploy (default) @ ctsms-web ---
[INFO]
[INFO] --- maven-install-plugin:2.3.1:install (default-install) @ ctsms-web ---
[INFO] Installing /ctsms/build/ctsms/web/target/ctsms-1.8.1.war to /root/.m2/repository/org/phoenixctms/ctsms/ctsms-web/1.8.1/ctsms-web-1.8.1.war
[INFO] Installing /ctsms/build/ctsms/web/pom.xml to /root/.m2/repository/org/phoenixctms/ctsms/ctsms-web/1.8.1/ctsms-web-1.8.1.pom
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  18.514 s
[INFO] Finished at: 2022-06-04T05:36:47Z
[INFO] ------------------------------------------------------------------------
Phoenix CTMS 1.8.1 installation finished.
grep: /home/phoenix/install.log: No such file or directory

```

How do I create new users or get default logins since I didn't get any department password phrase?

Thanks

**Comment by rkrenn** [comment]
see https://github.com/phoenixctms/config-default/blob/master/install/init_database.sh:

```
DEPARTMENT_PASSWORD=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1)
USER_PASSWORD=$(cat /dev/urandom | tr -dc 'a-z' | fold -w 3 | head -n 1)
sudo -u ctsms /ctsms/dbtool.sh -cd -dlk MYdepartment -dp "$DEPARTMENT_PASSWORD"
sudo -u ctsms /ctsms/dbtool.sh -cu -dlk MYdepartment -dp "$DEPARTMENT_PASSWORD" -u "phoenix" -p "$USER_PASSWORD" -pp "INVENTORY_MASTER_ALL_DEPARTMENTS,STAFF_MASTER_ALL_DEPARTMENTS,COURSE_MASTER_ALL_DEPARTMENTS,TRIAL_MASTER_ALL_DEPARTMENTS,PROBAND_MASTER_ALL_DEPARTMENTS,USER_ALL_DEPARTMENTS,INPUT_FIELD_MASTER,MASS_MAIL_MASTER_ALL_DEPARTMENTS,INVENTORY_MASTER_SEARCH,STAFF_MASTER_SEARCH,COURSE_MASTER_SEARCH,TRIAL_MASTER_SEARCH,PROBAND_MASTER_SEARCH,USER_MASTER_SEARCH,INPUT_FIELD_MASTER_SEARCH,MASS_MAIL_MASTER_SEARCH"

echo "The department passphrase for 'my_department' when adding users with /ctsms/dbtool.sh is '$DEPARTMENT_PASSWORD'."
echo "Log in at https://$IP with username 'phoenix' password '$USER_PASSWORD'."
```

PS: seems there is something wrong with your deployment:
>`grep: /home/phoenix/install.log: No such file or directory`

we just tested it, is is not broken and should work
`Log in at https://10.0.0.16 with username 'phoenix' password 'hfd'.`

**Comment by carebmc** [comment]
I kept getting these warnings while the installation script was executing. System in running debian bullseye 64-bit on AWS EC2.

WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.dom4j.io.SAXContentHandler (file:/var/lib/tomcat9/webapps/ROOT/WEB-INF/lib/dom4j-1.6.1.jar) to method com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser$LocatorProxy.getEncoding()
WARNING: Please consider reporting this to the maintainers of org.dom4j.io.SAXContentHandler
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

Re-ran part of the shell script you copied above with Mydepartment1 and phoenix1. I still got the same warnings but now I can login with phoenix1 and the password in $USER_PASSWORD.

**Comment by rkrenn** [comment]
the illegalreflection warnings are unrelated.

if you can launch the install.sh script like this https://github.com/phoenixctms/install-debian/blob/master/phoenix_install , it will write the install.log properly. we otherwise need to test it on that AWS image.

can you reproduce the problem on your local virtualbox installation? https://www.phoenixctms.org/installation/

**Comment by rkrenn** [comment]
ok you need to launch install.sh and redirect the output to install.log using `tee`, see https://github.com/phoenixctms/install-debian/blob/master/phoenix_install otherwise the credentials cannot be `grep`ped at last, and you just see 
`grep: /home/phoenix/install.log: No such file or directory`

**Comment by rkrenn** [comment]
these warning will be gone with new java/debian 12.

```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.dom4j.io.SAXContentHandler (file:/var/lib/tomcat9/webapps/ROOT/WEB-INF/lib/dom4j-1.6.1.jar) to method com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser$LocatorProxy.getEncoding()
WARNING: Please consider reporting this to the maintainers of org.dom4j.io.SAXContentHandler
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```

see https://github.com/phoenixctms/ctsms/issues/308
