### ISSUE TITLE
Reset expired user's password for user with priviledge to set passwords - link to issue #172

### ISSUE THREAD

**Issue by codonAG2** [phoenixctms/ctsms#268]
Hi,
We do have the same problem again as in closed issue #172. However, the solution below did not work this time.
Any idea what we can do to reset the admin password?
...
   for now it is easiest to create a temporary user (with local authentication), and then use it to change the expired user's password.

so to create such temporary "phoenix1" user (with priviledge to set passwords), log in to the phoenix VM console and run below command (taken from install.sh):

```
sudo -u ctsms /ctsms/dbtool.sh -cu -dlk <MY_DEPARTMENT> -dp <DEPARTMENT_PASSWORD> -u "phoenix1" -p <USER_PASSWORD> -pp "INVENTORY_MASTER_ALL_DEPARTMENTS,STAFF_MASTER_ALL_DEPARTMENTS,COURSE_MASTER_ALL_DEPARTMENTS,TRIAL_MASTER_ALL_DEPARTMENTS,PROBAND_MASTER_ALL_DEPARTMENTS,USER_ALL_DEPARTMENTS,INPUT_FIELD_MASTER,MASS_MAIL_MASTER_ALL_DEPARTMENTS,INVENTORY_MASTER_SEARCH,STAFF_MASTER_SEARCH,COURSE_MASTER_SEARCH,TRIAL_MASTER_SEARCH,PROBAND_MASTER_SEARCH,USER_MASTER_SEARCH,INPUT_FIELD_MASTER_SEARCH,MASS_MAIL_MASTER_SEARCH"
```

- <MY_DEPARTMENT> : your department name (ie. "my_department")
- <DEPARTMENT_PASSWORD> : the passphrase of yourdepartment, see last line of /home/phoenix/install.log  
- <USER_PASSWORD> : the password of your new "phoenix1" user

there is also an interactive form of the command:

```
sudo -u ctsms /ctsms/dbtool.sh --create_user_interactive
```

after logging into the webUI with the phoenix1 user, search&open your expired user, and set a fresh password.

_Originally posted by @rkrenn in https://github.com/phoenixctms/ctsms/issues/172#issuecomment-848645468_

**Comment by rkrenn** [comment]
what exactly is the issue

- did creating the separate user failed?
- or is there an error when setting the topical user's password?

pls also note you can simply disable password expiration.

--
support@phoenixctms.org

**Comment by codonAG2** [comment]
Hi,
The department password seems to be the issue.
We have been reading it from the install.log about 15 times. See attached screenshot.

Best regards,
Anja







-------- Ursprüngliche Nachricht --------
Von: Rene Krenn ***@***.***>
Datum: 24.08.23 11:31 (GMT+01:00)
An: phoenixctms/ctsms ***@***.***>
Cc: "Anja Kämpf Dr." ***@***.***>, Author ***@***.***>
Betreff: Re: [phoenixctms/ctsms] Reset expired user's password for user with priviledge to set passwords - link to issue #172 (Issue #268)


what exactly is the issue

  *   did creating the separate user failed?
  *   or is there an error when setting the topical user's password?

pls also note you can simply disable password expiration.

--
***@***.******@***.***>

**Comment by codonAG2** [comment]
![phoenix2 (1)](https://github.com/phoenixctms/ctsms/assets/79833229/3b60ee02-a72a-4d1b-90ff-65e8ebf04f2e)

**Comment by rkrenn** [comment]
pls try without the quotes.

also note that the $ in "Passw0rd$09" will try to do a variable interpolation.

**Comment by rkrenn** [comment]
did you manage to sort it out?

**Comment by codonAG2** [comment]
Sorry, but the admin user is not available until 11-09. I will send an update asap. Thanks for the hint so far.

**Comment by rkrenn** [comment]
> If not we would have to setup the phoenix instance again.

then your department password got lost. you could create another department - the consequence is that you cannot read PII (name, DoB, addresses, ..) of subjects of other departments. but maybe you did not enter these data anyway, as usual for CDMS use. and pls turn of user password expiries then.

> I know you can re-import the CRF setup but what about data and what do we have to take care of to do so?

yes you can re-import eCRF setup AND also data.

- https://github.com/phoenixctms/ctsms/issues/104
- https://github.com/phoenixctms/bulk-processor/pull/9
- https://github.com/phoenixctms/ctsms/pull/171

just export the eCRF data, then take one of the "horizontal" format and import it using the importer job:

![grafik](https://github.com/phoenixctms/ctsms/assets/17864099/f56d4f45-0b2d-4863-892e-9d3120137c64)

**Comment by codonAG** [comment]
We installed a new phoenixCTMS Server and will import the data from the old one.

Issue can be closed.
