### ISSUE TITLE
Running tests

### ISSUE THREAD

**Issue by Katerina1507** [phoenixctms/ctsms#271]
Hello. 
I'm trying to run tests and find bugs which were removed during creating project (make some kind of Analysis).  But I'm stuck on it.

**Comment by rkrenn** [comment]
there are 2 testsuites provided so far: 
- https://github.com/phoenixctms/ctsms/pull/262
- https://github.com/phoenixctms/ctsms/pull/249

you can find the command to run them here: https://github.com/phoenixctms/ctsms/blob/master/.github/workflows/run_selenium_test.sh

**Comment by Katerina1507** [comment]
thanks for links.
