### ISSUE TITLE
DBTool.java and goto Run Excepetion

### ISSUE THREAD

**Issue by wisty** [phoenixctms/ctsms#272]
Missing required option: [-puj task: purge old user journal records, -tdt task: delete trial, -cdpu task: change department password (user authentication), -pdudu task: perform deferred delete of user items, -ios task: import ops systematics, -idtdf task: (migration) initialize decrypted trial documents and files, -idplsr task: (migration) initialize decrypted enrollment status 'reason', -epd task: export permission definitions as csv/text file, -ia task: import asp and substances, -ib task: import bank identifications from csv/text file, -ic task: import country names from csv/text file, -ipd task: import permission definitions from csv/text file, -ie task: import eCRFs, eCRF fields, input fields and selection set values, -isdf task: import documents and files for a staff entity, -epj task: export proband journal, -epl task: export a trial's proband list, -cdc task: delete course, -tdef task: delete eCRF field, -upd task: migrate a proband to another department, -cdi task: create new department (interactive), -is task: import street names from csv/text file, -it task: import titles from csv/text file, -epib task: export proband inventory bookings of trials, -impi task: import proband image file mime types from csv/text file, -icdf task: import documents and files for a course entity, -cdp task: change department password, -iz task: import zip codes from csv/text file, -sda task: scan deferred delete of all entity items, -sdc task: delete criteria, -cdpi task: change department password (interactive), -ecpl task: export proband letters by criteria, -cui task: create new user (interactive), -ifdssv task: delete selection set value, -rp task: remove probands pending for auto-delete, -sds task: delete staff, -eif task: export input field and selection set values, -rcdf task: remove all files of a course entity, -iif task: import input fields and selection set values, -eij task: export inventory journal, -eifj task: export input field journal, -pifj task: purge old input field journal records, -imsi task: import input staff image file mime types from csv/text file, -iai task: import alpha ids, -imjf task: import job data file mime types from csv/text file, -smm task: send mass mails, -iis task: import icd systematics, -epdt task: export permission definition template as csv/text file, -mmdmm task: delete mass mail, -eat task: export eCRF audit trail, -sm task: scan for missing external files, -sn task: send notifications, -so task: scan for orphaned external files, -cd task: create new department, -pdmmdmm task: perform deferred delete of mass mail items, -irl task: import (stratification) randomization lists (including blinded data), -pdidi task: perform deferred delete of inventory items, -h task: print help, -i task: initialize db by insertig required setup records, -emmj task: export mass mail journal, -ppj task: purge old proband journal records, -ipapf task: (migration) initialize proband address province fields, -pmmj task: purge old mass mail journal records, -rtdf task: remove all files of a trial entity, -ijsmc task: (migration) initialize journal system message code fields, -cu task: create new user, -rpdf task: remove all files of a proband entity, -rdj task: execute daily jobs, -esj task: export staff journal, -pdifdif task: perform deferred delete of input field items, -dm task: scan for missing external files and delete references from DB, -do task: scan for orphaned external files and delete them, -ecj task: export course journal, -rmj task: execute monthly jobs, -pij task: purge old inventory journal records, -evsa task: export visit schedule appointments, -iidf task: import documents and files for an inventory entity, -ecr task: export search results, -icp task: import criterion properties tables, -pdsds task: perform deferred delete of staff items, -etj task: export trial journal, -pscj task: purge old criteria journal records, -ee task: export eCRFs, eCRF fields, input fields and selection set values, -idi task: delete inventory, -pdifdssv task: perform deferred delete of selection set value items, -imifi task: import input field image file mime types from csv/text file, -ifdif task: delete input field, -imcc task: import course certificate file mime types from csv/text file, -ipif task: (migration) initialize proband image fields, -rsdf task: remove all files of a staff entity, -escj task: export criteria journal, -euj task: export user journal, -imc task: import course file mime types from csv/text file, -eccv task: export CVs by criteria, -imi task: import inventory file mime types from csv/text file, -rwj task: execute weekly jobs, -psj task: purge old staff journal records, -udu task: delete user, -pdtdt task: perform deferred delete of trial items, -eej task: export ecrf journal of a trial, -ridf task: remove all files of an inventory entity, -imp task: import proband file mime types from csv/text file, -ims task: import staff file mime types from csv/text file, -imt task: import trial file mime types from csv/text file, -pdpdp task: perform deferred delete of proband items, -eep task: export eCRFs by trial, -pdtdef task: perform deferred delete of eCRF field items, -pcj task: purge old course journal records, -ipdf task: import documents and files for a proband entity, -pdtde task: perform deferred delete of eCRF items, -itdf task: import documents and files for a trial entity, -pdtdi task: perform deferred delete of inquiry items, -pdsdc task: perform deferred delete of criteria items, -ptj task: purge old trial journal records, -vpe task: validate pending ecrfs, -pda task: perform deferred delete of all items, -ldd task: load db with demo data records, -rmmdf task: remove all files of a mass mail entity, -immdf task: import documents and files for a mass mail entity, -puidp task: (migration) import permission definitions from csv/text file, add the user identity department permission and export as csv/text file, -tde task: delete eCRF, -immm task: import mass mail file mime types from csv/text file, -pdcdc task: perform deferred delete of course items, -tdi task: delete inquiry, -ipcf task: (migration) initialize proband comment fields, -ioc task: import ops codes, -eccpl task: export course participant lists by criteria, -pdp task: delete proband, -pn task: prepare notifications]

**Comment by rkrenn** [comment]
seems you did not provide any task option. what were you trying to run?

here you can find some example invocations of the dbtool: https://github.com/phoenixctms/ctsms/blob/master/.github/workflows/init_database.sh
