### ISSUE TITLE
eCRF csv horizontal export: value instead of boolean variable

### ISSUE THREAD

**Issue by codonAG2** [phoenixctms/ctsms#275]
For csv horizontal outputs each selection set value of input fields of selection type results in a dedicated boolean variable (true: item selected, false: item not selected). Is there an option to get a horizontal csv output not with the boolean variable but with the actual value set under selection set values tab in the create eCRF input field window? As in the example below values are set to 1, 2, 3 but csv output is not given as value but boolean variable. Is there an option to get an output with value when an item is selected and empty result when no item is selected, e.g. in this case ;;2;;?

![image](https://github.com/phoenixctms/ctsms/assets/79833229/ad030816-2265-4668-bb2d-cca2f4baf492)
![image](https://github.com/phoenixctms/ctsms/assets/79833229/fe21ad18-b6e8-494d-869f-931f987e9906)

**Comment by rkrenn** [comment]
yes, you can configure this on your own, see https://github.com/phoenixctms/config-default/blob/master/bulk_processor/CTSMS/BulkProcessor/Projects/ETL/EcrfExporter/settings.yml

```
col_per_selection_set_value: 1
selection_set_value_separator: ', '
```

so you either edit that settings.yml, or you create a new one (eg. mysettings.yml). for the latter, you can then add another job type record in the job_types database table (eg. name it "my eCRF export"), so you will be able to select it in the UI. for the command line of that job type you can then refer to your mysettings.yml.

**Comment by codonAG2** [comment]
Thanks, this should work for us.
