### ISSUE TITLE
problems with deletion of eCRF fields

### ISSUE THREAD

**Issue by asya-asya** [phoenixctms/ctsms#28]
During an attempt to delete one of the eCRF fields, an error message was raised:
"reson for deletion required".
Where this reason should be specified? An attempt to  to use "Comment" field did not help, though may be  some special format of the input is required for the deletion reason.
![err-del-crf-field-2](https://user-images.githubusercontent.com/49716780/56281980-48c7c980-610e-11e9-96ac-57be4dc5fdfa.PNG)

**Comment by rkrenn** [comment]
you should see the prompt in the comfirmation pop-up. this is an issue, we prepare a fix shortly.
to workaround meanwhile you can set 

ecrf_field_deferred_delete = true

in /ctsms/properties/org../settings.properties.

To finally delete the fields, you can register a cron job for

/ctsms/dbtool.sh --perform_deferred_delete_ecrf_field

**Comment by rkrenn** [comment]
fixed by https://github.com/phoenixctms/ctsms/commit/58334ae6dc4b47d4e80868e8b7e5832236b7c2f1
