### ISSUE TITLE
Authentication error after first successful login 

### ISSUE THREAD

**Issue by wolass** [phoenixctms/ctsms#3]
I have logged once into the system using the provided data. but then I got logged out and the login information does not work anymore (captcha is showing up now with the second loggin attempt). Is this an intended behaviour? I did not change any passwords after logging in.

**Comment by rkrenn** [comment]
>Is this an intended behaviour?

yes its one-time password; used up after the first login.

you can from cli create another user, but need the "department passphrase" printed at the end of the installation, eg "The department passphrase for 'my_department' when adding users with /ctsms/dbtool.sh is 'M1JYuTkNkYKMfatXOTa7KNsdabZthLHr'."

run the below command after replacing $DEPARTMENT_PASSWORD with your dept passphrase, and $USER_PASSWORD with the desired password for the new additional user phoenix1.

sudo -u ctsms /ctsms/dbtool.sh -cu -dlk my_department -dp "$DEPARTMENT_PASSWORD" -u "phoenix1" -p "$USER_PASSWORD" -pp "INVENTORY_MASTER_ALL_DEPARTMENTS,STAFF_MASTER_ALL_DEPARTMENTS,COURSE_MASTER_ALL_DEPARTMENTS,TRIAL_MASTER_ALL_DEPARTMENTS,PROBAND_MASTER_ALL_DEPARTMENTS,USER_ALL_DEPARTMENTS,INPUT_FIELD_MASTER,INVENTORY_MASTER_SEARCH,STAFF_MASTER_SEARCH,COURSE_MASTER_SEARCH,TRIAL_MASTER_SEARCH,PROBAND_MASTER_SEARCH,USER_MASTER_SEARCH,INPUT_FIELD_MASTER_SEARCH"

**Comment by rkrenn** [comment]
you can override the default session timeouts from https://github.com/phoenixctms/ctsms/blob/master/web/src/main/properties/org/phoenixctms/ctsms/web/settings.properties by creating an empty file /ctsms/properties/org/phoenixctms/ctsms/web/settings.properties, and adding adjusted values for

#timeouts in minutes:
session_timeout=10
session_timeout_trusted=180

**Comment by rkrenn** [comment]
change to not use one-time passwords any more when creating root users via CLI.

https://github.com/phoenixctms/ctsms/commit/85396fc72de96464fa7486de8423ee1a5af717c6

closing.
