### ISSUE TITLE
installation script does not print the password at the end of installation

### ISSUE THREAD

**Issue by jwcasl** [phoenixctms/ctsms#300]
We installed Phoenix following the directions here on a fresh Debian 11 virtual machine (on TrueNAS Scale Cobia). At the end of the installation, it said "grep: /home/phoenix/install.log: No such file or directory" instead of printing the randomly generated password. Is there a way to find that password, set a new password, or could you let us know what we did wrong? Looking at /home there is no subdirectory called phoenix. We then tried creating a user called phoenix so that /home/phoenix exists on a fresh Debian 11 virtual machine and installed again, but that didn't change anything. Thank you for your help.

**Comment by rkrenn** [comment]
>/home/phoenix/install.log

it presumes you run it as "phoenix" user

**Comment by jwcasl** [comment]
I tried it again logged in as the phoenix user (created as the only user during Debian 11 install) but still the same result unfortunately. It still cannot find the install.log to print the credentials. Thanks again for any insight you can give.

**Comment by rkrenn** [comment]
you need to `tee` into install.log, when you run install.sh manually. see the bootstrap https://github.com/phoenixctms/install-debian/blob/master/phoenix_install used in the phoenix .ova

**Comment by rkrenn** [comment]
in other words: run `sudo ~/install.sh 2>&1 | tee ~/install.log` instead of just `sudo install.sh`

**Comment by jwcasl** [comment]
Thank you very much. I'll give that a try. It would be great if the instructions can be updated with this as well.

**Comment by jwcasl** [comment]
This worked! Thanks again!
