### ISSUE TITLE
Import error during eCRF Data Import

### ISSUE THREAD

**Issue by codonAG** [phoenixctms/ctsms#325]
We tried an import of the eCRF data and get following error message
![error](https://github.com/user-attachments/assets/5254e136-3a5e-4386-9966-ba41693e1fd5)

The user my_department_cron exists and I set the password for the user on the web page. 
![users](https://github.com/user-attachments/assets/fcd5601d-a505-4d40-b7ae-4b3223ece888)

The password is also setted in the config.job.cfg
`phoenix@phoenixctms:/ctsms/bulk_processor/CTSMS/BulkProcessor/Projects/ETL/EcrfImporter$ cat config.job.cfg
##general settings:
#working_path = /ctsms/bulk_processor/output/ecrf_importer
enablemultithreading = 1

##gearman/service listener config:
jobservers = 127.0.0.1:4730

##Phoenix PostgreSQL connectivity - "ctsms" db:
ctsms_host = 127.0.0.1
ctsms_port = 5432
ctsms_databasename = ctsms
ctsms_username = ctsms
ctsms_password = ctsms

##ctsms REST-API connectivity:
ctsmsrestapi_uri = http://127.0.0.1:8080/rest
ctsmsrestapi_username = my_department_cron
ctsmsrestapi_password = F7M0pbaQ
ctsmsrestapi_realm = api

##sending email:
emailenable = 0
erroremailrecipient =
warnemailrecipient =
completionemailrecipient =
doneemailrecipient =

smtp_server=
smtpuser=
smtppasswd=

##logging:
fileloglevel = OFF
screenloglevel = OFF
screenlogstderr = 0
emailloglevel = INFO
phoenix@phoenixctms:/ctsms/bulk_processor/CTSMS/BulkProcessor/Projects/ETL/EcrfImporter$ ^C
phoenix@phoenixctms:/ctsms/bulk_processor/CTSMS/BulkProcessor/Projects/ETL/EcrfImporter$ cat config.job.cfg
##general settings:
#working_path = /ctsms/bulk_processor/output/ecrf_importer
enablemultithreading = 1

##gearman/service listener config:
jobservers = 127.0.0.1:4730

##Phoenix PostgreSQL connectivity - "ctsms" db:
ctsms_host = 127.0.0.1
ctsms_port = 5432
ctsms_databasename = ctsms
ctsms_username = ctsms
ctsms_password = ctsms

##ctsms REST-API connectivity:
ctsmsrestapi_uri = http://127.0.0.1:8080/rest
ctsmsrestapi_username = my_department_cron
ctsmsrestapi_password = F7M0pbaQ
ctsmsrestapi_realm = api

##sending email:
emailenable = 0
erroremailrecipient =
warnemailrecipient =
completionemailrecipient =
doneemailrecipient =

smtp_server=
smtpuser=
smtppasswd=

##logging:
fileloglevel = OFF
screenloglevel = OFF
screenlogstderr = 0
emailloglevel = INFO
`

**Comment by codonAG** [comment]
the user exists only once.

**Comment by rkrenn** [comment]
ok let us know if the issue also persits on a vanilla deployment, we will then investigate if there is a problem with the factory setup.

**Comment by codonAG** [comment]
How can I take a vanilla deployment?

**Comment by rkrenn** [comment]
just install it from scratch ( https://www.phoenixctms.org/installation/ ) separately, and try your setup+import there.

**Comment by rkrenn** [comment]
verified, works (see below).
if you need further assistance with upgrading phoenix instances, contact sales@phoenixctms.org.

closing ticket.

![grafik](https://github.com/user-attachments/assets/e0555765-965a-4d00-aa61-bcd4dc746bb5)
