### ISSUE TITLE
Milestones for invoicing

### ISSUE THREAD

**Issue by ArriFerrari** [phoenixctms/ctsms#4]
An important component of a complete CTMS seems to be missing. The system should be setup to help keep on top of site payments. e.g., when an eCRF is completed, a corresponding tally of amount owed is updated. Have I missed this feature, or is it still in development?

**Comment by rkrenn** [comment]
Currently, there is extensive coverage for managing compensation payments (aka "reimbursements") to trial participants. we had no need so far for what you describe as "site payments".

we can however add what you suggest, ie.
1. introducing another property (eg, "costs") for eCRF items (see a trial's eCRF tab).
2. a ecrf is considerred as done when it is set to a status with done = true (see database table "ecrf_status")
3. a summary list view (similar to the reimbursemt overview) showing a list of trials and corresponding total "cost" sums for their eCRFs with done status.

Does that fit? Pls refine otherwise.

**Comment by ArriFerrari** [comment]
Your idea of costs for eCRF items would be perfect. When working for a CRO,
you usually pay the staff of the clinical site separately from the patient
compensation.
We also usually give the clinical site a bonus if they have a certain
percentage (e.g., 80% or more) of eCRFs in the visits that are due complete
at the year end for a given patient. It’s usually called an “annual
compliance bonus”.

**Comment by ArriFerrari** [comment]
That’s exactly what I needed!
I’m impressed that you got it so quickly!
All the best,
Arri Morris

**Comment by rkrenn** [comment]
urw,

>I’m impressed that you got it so quickly!

the change request was quite precise and fits nicely (this time) to what already was prepared.
maybe you want to try it out now and report back (or even capterra review?), so we can close this one.

**Comment by ArriFerrari** [comment]
It will take me some time to get to this, I am traveling to clinics all
week for site initiation and monitoring visits. Judging by the screenshots,
and your description, it looks like you could close this request now and
I’ll do a full write up on Capterra as soon as I can :)

**Comment by rkrenn** [comment]
>I’m using a “droplet” from Digital Ocean. They have Ubuntu 16.04.4 (64-bit) with just the bare essentials.

i tested it now:
- in VirtualBox, i installed ubuntu from .iso http://releases.ubuntu.com/16.04/ubuntu-16.04.5-server-amd64.iso
- 4gb ram, 20gb hdd, 1vCPU, *important*: set LAN Adapter from "NAT" to "Bridged". i left everything else as is
- i used the standard settings suggested by the ubuntu installer. no http proxy; standard packages only (in particular don't install http or postgres, the installer will add whatever is missing, with proper version)
- created a user "phoenix", password "phoenix"
 
after booting, i logged in with user "phoenix" and executed

`sudo apt-get -y install wget ca-certificates`
`sudo wget https://raw.githubusercontent.com/phoenixctms/install-debian/master/phoenix_install -O ~/phoenix_install`
`sudo chmod 755 ~/phoenix_install`
`sudo su -`
`/home/phoenix/phoenix_install`

works right away.
