### ISSUE TITLE
Changing Tooltip on/off results in navigation jump

### ISSUE THREAD

**Issue by laborg** [phoenixctms/ctsms#55]
Firefox 66.0.5 on Ubuntu 19.04

- Navigate to a trial
- select `eCRFs` tab, Tooltip is on:
![image](https://user-images.githubusercontent.com/9527104/58087829-a8a80900-7bc1-11e9-849a-b3ef01a98fbb.png)
 - switch Tooltip off and wait for a couple of seconds.
 - the following page is loaded automatically 
![image](https://user-images.githubusercontent.com/9527104/58087958-f6bd0c80-7bc1-11e9-8033-c33f4b2a871e.png)

That's rather unexpected.

**Comment by rkrenn** [comment]
superseeded by https://github.com/phoenixctms/ctsms/issues/49 , full re-login and reload of all open tabs will be enforced then.

**Comment by laborg** [comment]
Behaviour in dedicated user page isn't surprising anymore.
