### ISSUE TITLE
Does not install correctly

### ISSUE THREAD

**Issue by RohitJain13** [phoenixctms/ctsms#6]
I have downloaded the VirtualBox image and tried to make it work, and also installed VirtualBox images of the Debian and Ubuntu versions and followed the instruction to build and make it work.  But I have not been successful in doing so.  The latter two seemed to have compile errors and even though at the end they said I had to connect to this URL, that URL was not responsive.

**Comment by RohitJain13** [comment]
I got the VirtualBox to work

**Comment by rkrenn** [comment]
libdatetime-format-excel-perl install error fixed, thx for pointing.
