### ISSUE TITLE
Field picker synchronization problem

### ISSUE THREAD

**Issue by laborg** [phoenixctms/ctsms#70]
When adding multiple _unique_ fields to an ecrf in rapid succession (~3 per second), the page to where the fields are directed to states:

> ID 601244 already picked

Doing the same in a slow fashion the behaviour isn't observed. It seams that there is some kind of synchronization/queuing problem with the field picker.

**Comment by rkrenn** [comment]
could be solved by queuing ajax operations on selected items. but since this cannot cause any harm, i'l mark i as won't fix.
