### ISSUE TITLE
Excel export of audit trail is empty if there is only one entry

### ISSUE THREAD

**Issue by laborg** [phoenixctms/ctsms#71]
After entering data the first time into an ecrf field, the audit trail (via  shows one entry, as expected, for this field:
![image](https://user-images.githubusercontent.com/9527104/58563622-c1e92f00-822b-11e9-8274-51f81ca64b40.png)

When creating an excel export however this entry is missing. 
After changing the value of the field, both audit trail entries are exported.

Is this expected?

**Comment by rkrenn** [comment]
well, the list in the Dialog is backed by `EcrfFieldValueAuditTrailLazyModel`, which invokes `TrialService.getEcrfFieldValue()`. It returns the full history of saved values for that field.

while the export uses `ECRFFieldValueDaoImpl.getLog()` methods. there you find 

`ecrfFieldValueCriteria.add(Subqueries.lt(1l, subQuery));`

to include rows in the Excel only if there are 2 or more saved values (so the value was changed at least once). so the excel report was intended to contain the changes only. it would get huge if it lists every saved value (of all ecrfs) - even when no change happened. This would effectively be the same as a vertical eCRF data export then (including the historical values), which is possible separately with eCRF data exports (csv, sqlite, ..).
