### ISSUE TITLE
possibility to override PDFPainter implemenations

### ISSUE THREAD

**Issue by rkrenn** [phoenixctms/ctsms#92]
phoenix can render various PDF documents. While labels, background template, font types and margins/positions are all externalized to .properties files already, the actual rendering is implemented using pdfbox primitive drawing operations. Therefore eg. the CV PDF renderer implementation typically consists of 5 files (residing in the org.phoenixctms.ctsms.pdf package):

- https://github.com/phoenixctms/ctsms/blob/master/core/src/main/java/org/phoenixctms/ctsms/pdf/CVPDFBlock.java
- https://github.com/phoenixctms/ctsms/blob/master/core/src/main/java/org/phoenixctms/ctsms/pdf/CVPDFBlockCursor.java
- https://github.com/phoenixctms/ctsms/blob/master/core/src/main/java/org/phoenixctms/ctsms/pdf/CVPDFDefaultSettings.java
- https://github.com/phoenixctms/ctsms/blob/master/core/src/main/java/org/phoenixctms/ctsms/pdf/CVPDFLabelCodes.java
- https://github.com/phoenixctms/ctsms/blob/master/core/src/main/java/org/phoenixctms/ctsms/pdf/CVPDFSettingCodes.java
- https://github.com/phoenixctms/ctsms/blob/master/core/src/main/java/org/phoenixctms/ctsms/pdf/CVPDFPainter.java

it is desired to be able to configure a custom implementation by specifying external .java (or .class) files. if feasable, the same technique could also be used for org.phoenixctms.ctsms.excel.

**Comment by rkrenn** [comment]
https://github.com/phoenixctms/ctsms/pull/96
https://github.com/phoenixctms/config-default/pull/2
https://github.com/phoenixctms/install-debian/pull/5

**Comment by laborg** [comment]
Why not use itext and pdf templates to customize pdf printing?

**Comment by rkrenn** [comment]
templates would be straight-forward as expected for static content.
but then adding paragraphs with iterated content (and nested-iterated ...) is known as downside. eg. imagine an acrobat form for such alternate eCRF casebook renderer.
that's why apache fop / xls-fo might be more interesting.

the overload mechanism added with this change introduces flexibility while keeping it less invasive. externalized code is sandboxed to use the pdfrendering aproach+utils described in [docs](https://www.researchgate.net/publication/263412137_Design_and_Development_of_a_Web-Based_Clinical_Trial_Management_System) page 100pp.

an idea could be to extend this change, by introduce some alternative "interface" that does not restrict to a render technique. the the user can implement itext or fop stuff as required on his own (therefore should be ensured that the classpath from [Compile.java](https://github.com/phoenixctms/ctsms/blob/master/common/src/main/java/org/phoenixctms/ctsms/util/Compile.java) also grabs external .jar's). Such interface can be minimal, it would just expose accessors to handover the value object graphs as an input, and another one to get back the pdfdocument value object as an output.
