### ISSUE TITLE
enrollment states: shortcut to switch from "candidate" to "ongoing"

### ISSUE THREAD

**Issue by rkrenn** [phoenixctms/ctsms#95]

**Comment by Kalandus** [comment]
![received_444356872850613](https://user-images.githubusercontent.com/32850368/70793680-29b43100-1d9c-11ea-88a5-957f3b60aa86.jpeg)

**Comment by rkrenn** [comment]
https://github.com/phoenixctms/ctsms/pull/99/commits/b78ce7201fe94d6fd4ae419478b5247a687d0c06

**Comment by rkrenn** [comment]
![grafik](https://user-images.githubusercontent.com/17864099/71808761-eb462500-306e-11ea-8420-86fc293805a7.png)
